### ISSUE TITLE
Support srt integrated into mkv files

### ISSUE THREAD

**Issue by Pythalex** [mudbile/animocha#1]
It would be a time saver if Animocha detected SRTs files in MKV videos. A workaround is to manually extract them then adding them into animocha but it's not very user friendly.

**Comment by neauangle** [comment]
v0.0.1 should have supported SRT files in video files, but there was a lot of subtitle formats I arbitrarily and accidentally blocked, which has been (hopefully) fixed in [v0.0.2](https://github.com/mudbile/animocha/releases/tag/v0.0.2). Can you please verify this is the case with your video files?

**Comment by Pythalex** [comment]
Sorry I think I misunderstood my problem. From what I understand the subtitles embedded in my mkv files are a video (it has pixel dimensions and it can only be extracted via OCR by most extraction tools). So I don't think it's something you want to support anyway as it's not configurable.

**Comment by neauangle** [comment]
Ah yeah I getcha. In lieu of a way to perform the OCR on the fly I think it is just easier for users to do it themselves or find a separate subtitle file for the foreseeable future: it would be quite difficult to display subtitle A around an image-based subtitle B, and something like VLC Player will always be better for videos with a single image-based subtitle stream (Animocha offers no benefit).  That being the case, I'll close this particular issue now. 

Although I don't feel strongly about it enough to make an issue for Animocha, I will keep subtitle-OCR-on-the-fly in mind as a future project idea (assuming I can't find an existing solution) which I could then hook into Animocha. If you feel stronger about that addition than I do I encourage you to make a separate issue and I'll take that into consideration.
